services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: scats
      POSTGRES_PASSWORD: scats
      POSTGRES_DB: scats_development
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
